let quote = document.getElementById("quote");

function generateQuote(){
    let quotes = [ 
        "Be yourself; everyone else is already taken. – Oscar Wilde",
        "Two things are infinite: the universe and human stupidity. – Albert Einstein",
        "So many books, so little time. – Frank Zappa",
        "A room without books is like a body without a soul. – Cicero",
        "Be the change that you wish to see in the world. – Mahatma Gandhi",
        "If you tell the truth, you don't have to remember anything. – Mark Twain",
        "Always forgive your enemies; nothing annoys them so much. – Oscar Wilde",
        "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
        "Without music, life would be a mistake. – Friedrich Nietzsche",
        "We accept the love we think we deserve. – Stephen Chbosky",
        "It is never too late to be what you might have been. – George Eliot",
        "Do what you can, with what you have, where you are. – Theodore Roosevelt",
        "Life is what happens when you're busy making other plans. – John Lennon",
        "Everything you can imagine is real. – Pablo Picasso",
        "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
        "Believe you can and you're halfway there. – Theodore Roosevelt",
        "It does not matter how slowly you go as long as you do not stop. – Confucius",
        "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
        "You miss 100% of the shots you don’t take. – Wayne Gretzky",
        "I think, therefore I am. – René Descartes",
        "That which does not kill us makes us stronger. – Friedrich Nietzsche",
        "Life is really simple, but we insist on making it complicated. – Confucius",
        "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
        "A friend is someone who knows all about you and still loves you. – Elbert Hubbard",
        "We are all in the gutter, but some of us are looking at the stars. – Oscar Wilde",
        "You only live once, but if you do it right, once is enough. – Mae West",
        "Good friends, good books, and a sleepy conscience: this is the ideal life. – Mark Twain",
        "The fool doth think he is wise, but the wise man knows himself to be a fool. – William Shakespeare",
        "Imagination is more important than knowledge. – Albert Einstein",
        "I have a dream. – Martin Luther King Jr.",
        "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
        "Don’t cry because it’s over, smile because it happened. – Dr. Seuss",
        "We don’t see things as they are, we see them as we are. – Anaïs Nin",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
        "Dream big and dare to fail. – Norman Vaughan",
        "In the middle of every difficulty lies opportunity. – Albert Einstein",
        "The journey of a thousand miles begins with one step. – Lao Tzu",
        "It is our choices that show what we truly are, far more than our abilities. – J.K. Rowling",
        "If you’re going through hell, keep going. – Winston Churchill",
        "It always seems impossible until it’s done. – Nelson Mandela",
        "Don’t count the days, make the days count. – Muhammad Ali",
        "Turn your wounds into wisdom. – Oprah Winfrey",
        "Try not to become a man of success, but rather try to become a man of value. – Albert Einstein",
        "It is not length of life, but depth of life. – Ralph Waldo Emerson",
        "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
        "Happiness depends upon ourselves. – Aristotle",
        "The best way to predict your future is to create it. – Abraham Lincoln",
        "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
        "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
        "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
        "Great minds discuss ideas; average minds discuss events; small minds discuss people. – Eleanor Roosevelt",
        "Whether you think you can or you think you can’t, you’re right. – Henry Ford",
        "Work hard in silence, let success be your noise. – Frank Ocean",
        "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
        "Success is how high you bounce when you hit bottom. – George S. Patton",
        "Failure is simply the opportunity to begin again, this time more intelligently. – Henry Ford",
        "If opportunity doesn’t knock, build a door. – Milton Berle",
        "The secret of getting ahead is getting started. – Mark Twain",
        "The only place where success comes before work is in the dictionary. – Vidal Sassoon",
        "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
        "You must be the change you wish to see in the world. – Mahatma Gandhi",
        "To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
        "Don’t let yesterday take up too much of today. – Will Rogers",
        "It’s not what happens to you, but how you react to it that matters. – Epictetus",
        "To love and be loved is to feel the sun from both sides. – David Viscott",
        "Life is either a daring adventure or nothing at all. – Helen Keller",
        "Do not let making a living prevent you from making a life. – John Wooden",
        "The best way out is always through. – Robert Frost",
        "Everything has beauty, but not everyone sees it. – Confucius",
        "Don’t gain the world and lose your soul. – Bob Marley",
        "Learn as if you will live forever, live like you will die tomorrow. – Mahatma Gandhi",
        "It is better to fail in originality than to succeed in imitation. – Herman Melville",
        "The road to success and the road to failure are almost exactly the same. – Colin R. Davis",
        "I find that the harder I work, the more luck I seem to have. – Thomas Jefferson",
        "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
        "Opportunities don't happen. You create them. – Chris Grosser",
        "Don't be afraid to give up the good to go for the great. – John D. Rockefeller",
        "I never dreamed about success. I worked for it. – Estée Lauder",
        "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
        "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
        "Push yourself, because no one else is going to do it for you. – Unknown",
        "Great things never come from comfort zones. – Unknown",
        "Dream it. Wish it. Do it. – Unknown",
        "Success doesn’t just find you. You have to go out and get it. – Unknown",
        "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. – Unknown",
        "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
        "Wake up with determination. Go to bed with satisfaction. – Unknown",
        "Do something today that your future self will thank you for. – Unknown",
        "Little things make big days. – Unknown",
        "Don’t wait for opportunity. Create it. – Unknown",
        "It’s going to be hard, but hard does not mean impossible. – Unknown",
        "Don’t stop when you’re tired. Stop when you’re done. – Unknown",
        "Wake up with determination, go to bed with satisfaction. – Unknown"
         ];
      let rando =  Math.floor( Math.random() * quotes.length) ;
       let quoteSelected = quotes[rando];
      quote.innerHTML = `
         <h1 id="quote"><span>“</span>${quoteSelected}<span>”</span></h1>
      `;
}

